config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :articles
  
  root 'pages#home'
  get 'about', to: 'pages#about'
  
  resources :users  

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
    validates :name,  presence: true, length: {minimum: 3, maximum: 10}
    validates :password, presence: true, length: {minimum: 6, maximum: 20}
end  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:date, :time, :from, :pax, :paid, :user)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
    def about
    end
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController 
   before_action :set_user, only: [:edit, :update, :show, :destroy]
     
     def index 
       @users = User.all
     end
     
     def new
         @user = User.new 
     end 
     
     def create
      @user = User.new(user_params)
      if @user.save
       flash[:notice] = "New user has been created."
       redirect_to user_path(@user)
      else
       #flash[:notice] = "User HAS NOT been created."
       render :new 
      end
     end
     
     def edit
     end
     
     def update 
       if @user.update(user_params)
         flash[:notice] = "User information was updated."
         redirect_to user_path(@user)
       else 
          render 'edit'
       end
     end
     
     
    def show
    end
    
    def destroy
      @user.destroy
      flash[:notice] = "User has been deleted."
      redirect_to  users_path
    end
    
   
     private
       def set_user
         @user = User.find(params[:id])
       end
       
       def user_params
        params.require(:user).permit(:name, :password)
       end
      end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @article.description %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/_msgs.html.erb
<% flash.each do  |name, msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_top_menu.html.erb
<%= link_to 'Home', root_path %> | <%= link_to 'Article', articles_path %> | <%= link_to 'Users', users_path %> | <%= link_to 'Orders', orders_path %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/top_menu' %>
<div class="msgBlock"><%= render 'layouts/msgs' %></div>



<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.time_select :time %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_area :from %>
  </div>
  <div class="field">
    <%= f.label :pax %><br>
    <%= f.number_field :pax %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.check_box :paid %>
  </div>
  <div class="field">
    <%= f.label :user %><br>
    <%= f.select :user, User.all.collect { |u| [u.name] }, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>From</th>
      <th>Pax</th>
      <th>Paid</th>
      <th>User</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.date %></td>
        <td><%= order.time %></td>
        <td><%= order.from %></td>
        <td><%= order.pax %></td>
        <td><%= order.paid %></td>
        <td><%= order.user %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @order.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @order.time %>
</p>

<p>
  <strong>From:</strong>
  <%= @order.from %>
</p>

<p>
  <strong>Pax:</strong>
  <%= @order.pax %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @order.paid %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/pages/about.html.erb
<h1>About Alpha Blog</h1>
<p>This is the application we will be developing during the course</p>

<p>Here is some information about the application:</p>
<table width='500'>
    <tr>
        <td>Date created:</td>
        <td><b>August 11, 2016</b></td>
    </tr>
    <tr>
        <td>Last updated:</td>
        <td><b>August 12, 2016</b></td>
    </tr>
    <tr>
        <td>Author:</td>
        <td><b>Michael Levin</b></td>
    </tr>
    
</table>
<br>
<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<h1>Welcome to Alpha Blog App!</h1>
<p>This is the home page</p>

<%= link_to 'About', about_path %>

app/views/users/_form.html.erb
<div class="errBlock">
    <% if @user.errors.any? %>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    <% end %>
</div>

<%= form_for @user do |uf| %>
    <p>
        <%= uf.label :name %><br/>
        <%= uf.text_field :name %>
    </p>
    <p>
        <%= uf.label :password %><br/>
        <%= uf.text_field :password %>
    </p>
    <p>
        <%= uf.submit %>
    </p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User information</h1>

  <%= render 'form' %> 

<p><%= link_to 'Back to list', users_path %></p>

app/views/users/index.html.erb
<h1>List of users in the system</h1>
<%= link_to 'Add new user', new_user_path %>
<table>
  <tr>
    <th width="100">ID</th>
    <th width="100">Name</th>
    <th width="100">Password</th>
  </tr>
  <% @users.each do |u| %>
  <tr>
    <td><%= u.id %></td>
    <td><%= u.name %></td>
    <td><%= u.password %></td>
    <td><%= link_to 'Show', user_path(u) %></td>
    <td><%= link_to 'Edit', edit_user_path(u) %></td>
    <td><%= link_to 'Delete', user_path(u), method: :delete, data: {confirm: "Are you sure you want to delete this user?"} %></td>
  <% end %>
  </tr>
</table>

app/views/users/new.html.erb
<h1>New user</h1>

    <%= render 'form' %>

<p><%= link_to 'Back to list', users_path %></p>

app/views/users/show.html.erb
<h1>User information</h1>

<p>User name: <%= @user.name %></p>
<p>Password: <%= @user.password %> </p>
<br/>
<p><%= link_to 'Edit user', edit_user_path(@user) %></p>
<p><%= link_to 'Back to list', users_path %></p>